version: '2'

#networks:
#    default:
#        external:
#            name: w-ros_default
                
services:
                  
  odas:
    build: .
    image: wn1980/odas-server
    container_name: odas_server
    restart: unless-stopped
    command: stdbuf -o L bin/odaslive -c config/odaslive/respeaker_4_mic_array.cfg
    privileged: true
    devices:
      - "/dev/snd:/dev/snd"
    volumes:
      - "/dev/snd:/dev/snd"
      - "./asoundrc.txt:/root/.asoundrc:rw"
      - "./src:/root/src:rw"
      - "/etc/localtime:/etc/localtime:ro"
    ports:
      - "9000:9000"
      - "9001:9001"